import { BookOverview } from "./models/overview";

export const BOOKS: BookOverview[] = [
  { "name": "Genesis", "identifier": "Gen", "chapters": 50, "testament": "Old" },
  { "name": "Exodus", "identifier": "Exo", "chapters": 40, "testament": "Old" },
  { "name": "Leviticus", "identifier": "Lev", "chapters": 27, "testament": "Old" },
  { "name": "Numbers", "identifier": "Num", "chapters": 36, "testament": "Old" },
  { "name": "Deuteronomy", "identifier": "Deu", "chapters": 34, "testament": "Old" },
  { "name": "Joshua", "identifier": "Jos", "chapters": 24, "testament": "Old" },
  { "name": "Judges", "identifier": "Jdg", "chapters": 21, "testament": "Old" },
  { "name": "Ruth", "identifier": "Rut", "chapters": 4, "testament": "Old" },
  { "name": "1 Samuel", "identifier": "1Sa", "chapters": 31, "testament": "Old" },
  { "name": "2 Samuel", "identifier": "2Sa", "chapters": 24, "testament": "Old" },
  { "name": "1 Kings", "identifier": "1Ki", "chapters": 22, "testament": "Old" },
  { "name": "2 Kings", "identifier": "2Ki", "chapters": 25, "testament": "Old" },
  { "name": "1 Chronicles", "identifier": "1Ch", "chapters": 29, "testament": "Old" },
  { "name": "2 Chronicles", "identifier": "2Ch", "chapters": 36, "testament": "Old" },
  { "name": "Ezra", "identifier": "Ezr", "chapters": 10, "testament": "Old" },
  { "name": "Nehemiah", "identifier": "Neh", "chapters": 13, "testament": "Old" },
  { "name": "Esther", "identifier": "Est", "chapters": 10, "testament": "Old" },
  { "name": "Job", "identifier": "Job", "chapters": 42, "testament": "Old" },
  { "name": "Psalms", "identifier": "Psa", "chapters": 150, "testament": "Old" },
  { "name": "Proverbs", "identifier": "Pro", "chapters": 31, "testament": "Old" },
  { "name": "Ecclesiastes", "identifier": "Ecc", "chapters": 12, "testament": "Old" },
  { "name": "Song of Solomon", "identifier": "Sng", "chapters": 8, "testament": "Old" },
  { "name": "Isaiah", "identifier": "Isa", "chapters": 66, "testament": "Old" },
  { "name": "Jeremiah", "identifier": "Jer", "chapters": 52, "testament": "Old" },
  { "name": "Lamentations", "identifier": "Lam", "chapters": 5, "testament": "Old" },
  { "name": "Ezekiel", "identifier": "Ezk", "chapters": 48, "testament": "Old" },
  { "name": "Daniel", "identifier": "Dan", "chapters": 12, "testament": "Old" },
  { "name": "Hosea", "identifier": "Hos", "chapters": 14, "testament": "Old" },
  { "name": "Joel", "identifier": "Jol", "chapters": 3, "testament": "Old" },
  { "name": "Amos", "identifier": "Amo", "chapters": 9, "testament": "Old" },
  { "name": "Obadiah", "identifier": "Oba", "chapters": 1, "testament": "Old" },
  { "name": "Jonah", "identifier": "Jon", "chapters": 4, "testament": "Old" },
  { "name": "Micah", "identifier": "Mic", "chapters": 7, "testament": "Old" },
  { "name": "Nahum", "identifier": "Nam", "chapters": 3, "testament": "Old" },
  { "name": "Habakkuk", "identifier": "Hab", "chapters": 3, "testament": "Old" },
  { "name": "Zephaniah", "identifier": "Zep", "chapters": 3, "testament": "Old" },
  { "name": "Haggai", "identifier": "Hag", "chapters": 2, "testament": "Old" },
  { "name": "Zechariah", "identifier": "Zec", "chapters": 14, "testament": "Old" },
  { "name": "Malachi", "identifier": "Mal", "chapters": 4, "testament": "Old" },
  { "name": "Matthew", "identifier": "Mat", "chapters": 28, "testament": "New" },
  { "name": "Mark", "identifier": "Mrk", "chapters": 16, "testament": "New" },
  { "name": "Luke", "identifier": "Luk", "chapters": 24, "testament": "New" },
  { "name": "John", "identifier": "Jhn", "chapters": 21, "testament": "New" },
  { "name": "Acts", "identifier": "Act", "chapters": 28, "testament": "New" },
  { "name": "Romans", "identifier": "Rom", "chapters": 16, "testament": "New" },
  { "name": "1 Corinthians", "identifier": "1Co", "chapters": 16, "testament": "New" },
  { "name": "2 Corinthians", "identifier": "2Co", "chapters": 13, "testament": "New" },
  { "name": "Galatians", "identifier": "Gal", "chapters": 6, "testament": "New" },
  { "name": "Ephesians", "identifier": "Eph", "chapters": 6, "testament": "New" },
  { "name": "Philippians", "identifier": "Php", "chapters": 4, "testament": "New" },
  { "name": "Colossians", "identifier": "Col", "chapters": 4, "testament": "New" },
  { "name": "1 Thessalonians", "identifier": "1Th", "chapters": 5, "testament": "New" },
  { "name": "2 Thessalonians", "identifier": "2Th", "chapters": 3, "testament": "New" },
  { "name": "1 Timothy", "identifier": "1Ti", "chapters": 6, "testament": "New" },
  { "name": "2 Timothy", "identifier": "2Ti", "chapters": 4, "testament": "New" },
  { "name": "Titus", "identifier": "Tit", "chapters": 3, "testament": "New" },
  { "name": "Philemon", "identifier": "Phm", "chapters": 1, "testament": "New" },
  { "name": "Hebrews", "identifier": "Heb", "chapters": 13, "testament": "New" },
  { "name": "James", "identifier": "Jas", "chapters": 5, "testament": "New" },
  { "name": "1 Peter", "identifier": "1Pe", "chapters": 5, "testament": "New" },
  { "name": "2 Peter", "identifier": "2Pe", "chapters": 3, "testament": "New" },
  { "name": "1 John", "identifier": "1Jn", "chapters": 5, "testament": "New" },
  { "name": "2 John", "identifier": "2Jn", "chapters": 1, "testament": "New" },
  { "name": "3 John", "identifier": "3Jn", "chapters": 1, "testament": "New" },
  { "name": "Jude", "identifier": "Jud", "chapters": 1, "testament": "New" },
  { "name": "Revelation", "identifier": "Rev", "chapters": 22, "testament": "New" }
];
